### ISSUE TITLE
Show email in dashboard for registered participants

### ISSUE THREAD

**Issue by mdccxxix** [CodeShala/codeshala.org#23]
Show email in admin dashboard for registered participants.

**Comment by vipinkhushu** [comment]
Dashboard is the page students will see after they login, this is an unreleased feature. email is being printed in proposed view. See demo here http://test.codeshala.com/home

**Comment by mdccxxix** [comment]
This is awesome Vipin. Right now, I need emails of the registered candidates, it would be great if we can see emails of registered emails on the admin dashboard itself else admin need to go to each user profile to find out the email.

**Comment by vipinkhushu** [comment]
I will push fix for this soon, also send format in which you need emails to copy paste into Google admin... like comma separated.. i will add that feature there where you need to copy and paste emails

**Comment by vipinkhushu** [comment]
This issue was already fixed in https://github.com/CodeShala/codeshala.org/commit/c2fd71c4f3ba55969f6639e03515b5b0e274dd5a , Now pushed to production

Also now emails can be copied to clipboard directly on a button press in CSV format, this feature added in https://github.com/CodeShala/codeshala.org/commit/55d9e7664bdd56fe62da57cf67a9aa33f2ddaf43
